export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Faq} from './Faq'
export {default as LetsStart} from './LetsStart'
export {default as BusinessAccount} from './BusinessAccount'