export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Faq} from './Faq'
export {default as Landing} from './Landing'
export {default as Cta} from './Cta'