import Head from 'next/head'
import NotFound from '@/components/NotFound'

const index = () => {
  return (
    <section className="h-[400px] w-full flex flex-col items-center justify-center" >
         <Head>
        <title>Loaningo, Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <NotFound />
{/* <h1 className="text-3xl text-dimgot" >Nothing here ..!</h1>
<p className="  text-dimgot py-3" >This page isn't available.</p> */}
    </section>
  )
}

export default index