import Head from 'next/head'
import Image from 'next/image'
import {Navbar, Hero, Faq, LetsStart, BusinessAccount} from '@/components'


export default function Home() {
  return (
    <>
      <Head>
        <title>Gotimate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Hero />
        <Faq />
        <LetsStart />
        <BusinessAccount/>
      
    </>
  )
}
